.gitignore, src/index.js
Enables listeners to all RUM events, not just the sampled ones.
Using RUM for instrumentation and forwarding the RUM events of interest to WebSDK client-side depends on this feature being present in the boilerplate code.
Same is applicable for conversion tracking using RUM https://github.com/adobe/franklin-rum-conversion/tree/main and then forwarding the conversion events to Analytics via WebSDK.
Code changes could not be extracted to an isolated library/file as the logic resides in the sampleRUM method and there is no extension point available atm.
Code changes merged in boilerplate via https://github.com/adobe/helix-project-boilerplate/pull/247.
Already used for:
- BambooHR: https://github.com/BambooHR/bamboohr-website/blob/main/scripts/scripts.js#L158-L160
- WKND: …
=> feat: enable listeners to all RUM events, not just the sampled ones

src/index.js
#87 
Remove from the payload the properties that are unknown to RUM service
=> [87] feat: filter unknown properties out from the beacon

src/index.js
See https://cq-dev.slack.com/archives/C04KT8BJR19/p1695188879278689?thread_ts=1694701902.855299&cid=C04KT8BJR19
This assumes that the origin CDN forwards all requests going to `**/.rum/**` to `https://rum.hlx.page/.rum/$2`
As this is not yet the case with `hlx.live` and `hlx.page` we need to think about how to distribute this code variant to users where the routing has been enabled on the CDN level
#99
=> [99] enable configurable base URL for beacon destination

src/index.js
=> fix: change id generation

rollup.config.js
When RUM is used in Standalone mode and the script is not loaded with `type="module"` the function sampleRUM is defined in the global scope.
This is not desirable and will cause issues if other scripts, such as enhancer, declare the same variable name in the global scope.
With this PR we wrap `sampleRUM` and its invocation in their own function, restricting the scope of the variables defined, but only in the Standalone mode, without modifying the structure for Edge Delivery Services projects.
=> chore(standalone): wrap standalone as a iife

src/index.js
Sometimes error events don't have the expected structure, e.g. error is just a string `Script error` and that causes an exception as there is no `stack`.
The changes in this PR add a try catch block to avoid this situations.
=> fix: avoid exceptions on error tracking

src/index.js, test/sampleRUM-afterloadevent.test.html, test/sampleRUM-beforeloadevent.test.html, test/sampleRUM.test.js
@davidnuescheler and I were looking at the RUM data of the GenStudio and only few data are available. On top of low traffic, we discovered that the enhancer is not loaded.
Reason: the `load` event has already fired.
Relying on the `load` event is problematic, because we do not know when the script `rum-standalone.js` script is loaded. In the GenStudio case, it is pretty late. 
If people follow the instructions to load the script right after the LCP, there is not specific reason to wait for the `load` event to load the enhancer. 
If they add it pre-LCP, the costly DNS lookup and SSL handshake are already done anyway (i.e. to load `rum-standalone.js`), which is another reason to not wait for the `load` event.
For all those reasons, we should get rid of the listener on the `load` event and …
=> fix: immediately load the enhancer

src/index.js
We should not track the `pagesviewed` checkpoint, especially not track things in the session storage!
=> feat: remove pagesviewed

src/index.js, test/errors/errors.js, test/errors/sampleRUM.basic.error.custom.test.js, test/errors/sampleRUM.basic.error.test.js, test/errors/sampleRUM.real.error.test.js, test/errors/sampleRUM.real.function.error.test.js, test/errors/sampleRUM.unhandledrejection.noreason.test.js, test/errors/sampleRUM.unhandledrejection.obj.test.js, test/errors/sampleRUM.unhandledrejection.test.js, test/sampleRUM-error.test.js
While looking at the error tracking, I realized there are some inconsistencies like:
- if error occur in the HTML file, the source appears as ` at https://...` while if error occurs in a JS file it shows `functionname@https://...` - addressed by the PR
- we have a lot of `source: undefined error` (and no target) - while this might be the case for unhandled promise rejections, code could try to identify a better source and target for those cases.
I also wrote tests to cover all different scenarii.
=> feat: improve errors capture

docs/STANDALONE-ADVANCED-CONFIG.md, src/index.js, test/sampleRUM-enabled.test.js
This introduces a new global variable, `window.RUM_SAMPLING_RATE`, that can be set before loading the library to increase the sampling rate for specific use cases that require more data collected for short-term reporting.
For instance:
- when running an experiment in a 2-week time-frame and achieve statistical significance even with low traffic
- when running short-lived marketing campaign and wanting to collect enough data over a single weekend
For instance:
```js
window.SAMPLE_PAGEVIEWS_AT_RATE = 'high';
```
Or in an HTML context:
```html
<head>
<meta name="experiment" content="Foo"/>
<meta name="experiment-variants" content="/bar,/baz"/>
<script>window.SAMPLE_PAGEVIEWS_AT_RATE = document.head.querySelector('meta[name="experiment"]') ? 'high' : null</script>
<script …
```
=> feat(minirum): allow increasing the sampling rate up to 1/10 for specific use cases

package-lock.json, package.json, rollup.config.js
Adds the license to `rum-standalone.js` and `rum-standalone-404.js`.
=> fix: add missing license to packaged code

README.md, docs/STANDALONE-ADVANCED-CONFIG.md
This PR is a follow up of #202 , updating the docs
=> feat: Simplify script inclusion when using same domain

docs/RUM-IN-EDGE-DELIVERY-SERVICES.md
fixes the documentation issue raised in #208
=> docs(edge): point out not to call the function directly

docs/API.md
Carsten's comment in #208 mentioned that the docs imply that you should call this API directly. You should not.
=> docs(api): point out this is a private API

src/index.js, test/loading/enhance-manual-late.test.html
If `sampleRUM.enhance()` is called twice, enhancer code will be injected twice and we might have duplicate events.
=> feat: allow to enhance only once

src/404.js, src/index.js, src/standalone.js, test/sampleRUM-with-enhancer-version.test.html
Fixes: #203 
Allow users of standalone distribution to provide a specific enhancer version, and a md5 hash
=> feat(enhancer-version): allow selecting a specific enhancer version in standalone

src/standalone.js
_Moved from fork to main repo_
In cloud service depending on configuration we may not know the actual response status when injecting the RUM script, thus cannot determine if the 404 or standalone script should be included. This PR adds client-side code to determine the response status using the Performance API and trigger the 404 sampling when needed, effectively combining the 404 and standalone script into one.
The response code is read from the [PerformanceNavigationTiming](https://www.w3.org/TR/navigation-timing-2/#dom-performancenavigationtiming) object. The responseStatus is supported by modern browsers except for Safari. As a fallback the ServerTiming object is inspected for a status property which is read from a server-timing header which needs to be injected by the server, e.g. in …
=> Use Performance API to get response status and sample accordingly

README.md, src/standalone.js
Currently we create two scripts standalone and standalone-404 - which are mainly identical, with the exception that the latter is used for tracking 404 responses. With the recent introduction of using the navigation API into the standalone script, it makes sense to merge the functionality into a single script.
This patch uses the data-status attribute to inform the script of a 404 response, instead of using a separate script.
For now we should still create the standalone-404 until we can phase it out
=> feat(standalone): Use data attribute for 404 tracking (avoid separate script)

.renovaterc.json
Use new helix-bot capability (see https://github.com/adobe/helix-bot/issues/1573) to ignore psi check if renovate makes a PR on dev dependency.
=> chore(renovate): renovate PRs on dev dependencies do not trigger psi check

web-test-runner.config.js
This PR increases the browserStartTimeout for Firefox browsers to 120 seconds (from the default 60 seconds) to fix failing tests in CI environments. Both PR #243 and PR #244 have been failing with Firefox timeouts during test initialization, and this change should resolve that issue.
=> fix: increase browserStartTimeout for Firefox to 120s in CI tests

package.json, web-test-runner.config.js
Currently tests execution on Firefox is not properly working because Firefox does not start as expected.
I have created https://github.com/microsoft/playwright/issues/35183 and https://github.com/modernweb-dev/web/issues/2907.
In the meantime, I suggest to remove Firefox for the browser list and to create an issue to keep track to re-enable it when the bugs are fixed.
=> chore: disable tests on Firefox

src/index.js, test/sampleRUM-enabled.test.js
Fix #261
Use [crypto.getRandomValues](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/getRandomValues) (fully supported on all browsers) instead of `Math.random` which triggers security concerns - unjustified for this case but logic remains the same and will avoid security complains.
=> chore: get rid of Math.random for id generation

src/standalone.js
The standalone script is currently using the origin of the script source as RUM_BASE. With this patch, if a `data-post-path` attribute is set, this path will be appended to RUM_BASE.
=> feat: Allow path for posts to be set via data attribute

src/index.js, test/errors/sampleRUM.csp.violation.test.js, test/loading/enhance-module-csp.test.html
See description and comments at https://github.com/adobe/aem-boilerplate/pull/545.  This is meant to be the official PR to check for customer implementations blocking the helix-rum-enhancer from loading, and the changes made here to sampleRUM will flow to the copy in aem-boilerplate.  The other PR will be abandoned and was meant for early syntax review.
BEFORE - no test for CSP violation, no error checkpoint with csp source
https://main--helix-rum-js--adobe.aem.page/test/loading/enhance-module.test.html?rum=on
AFTER - test for CSP violation, error checkpoint with csp source
https://csp--helix-rum-js--adobe.aem.page/test/loading/enhance-module-csp.test.html?rum=on
=> Collect OpTel for CSP violations
